### ISSUE TITLE
Tracker: sign Ansible repositories asynchronously with Sigstore

### ISSUE THREAD

**Issue by mayaCostantini** [mayaCostantini/pulp_ansible#13]
**Is your feature request related to a problem? Please describe.**
As the pulp_ansible tasking system is mostly asynchronous, investigate on a way to make the Sigstore signing task for a repository asynchronous. This would be useful to reduce downtime when signing a large number of collections in a repository.

**Describe the solution you'd like**
- [x] Research existing implementations of asynchronous signing in other Sigstore clients
- [x] Identify calls that could potentially be made async and ones that could be blocking
- [x] Experiment with python client

**Describe alternatives you've considered**
Implement Sigstore signing as a synchronous task.

**Comment by mayaCostantini** [comment]
Fixed by https://github.com/mayaCostantini/pulp_ansible/pull/16
