### ISSUE TITLE
Sigstore + pulp_ansible integration tracker

### ISSUE THREAD

**Issue by mayaCostantini** [mayaCostantini/pulp_ansible#2]
To do:

- [ ] OIDC ambient credentials verify workflow
- [ ] OIDC ambient credentials sign workflow
- [ ] Allow users to use a private TUF root of trust
- [ ] Implement key pair signing
- [ ] Rekor offline verification with Rekor bundles
- [ ] Test with ansible-sign sigstore implementation when refactored with stable version of sigstore-python API
- [ ] Docs + guide on how to set up a Sigstore signing service
- [ ] Unit tests
- [ ] Tests on a GCloud environment
- [ ] Demo
